name: Docker Image CI

on:
  push:
    branches: master
    tags: '**'
  schedule:
  - cron: 0 0 * * 6

env:
  TAG_PREFIX: $([ ${GITHUB_REF#refs/*/} == "master" ] && echo "latest" || echo ${GITHUB_REF#refs/*/})

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_version: [56, 70, 71, 72, 73, 74, 80]
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      env:
        PHP_VERSION: ${{ matrix.php_version }}
      run: |
        export TAG_VERSION=${PHP_VERSION:0:1}.${PHP_VERSION:1:1}
        docker build . --file Dockerfile-${{ matrix.php_version }} --tag laradock/php-fpm:${{ env.TAG_PREFIX }}-${TAG_VERSION}      
        docker image ls

    - name: Push image to Docker hub
      if: success()
      env:
        PHP_VERSION: ${{ matrix.php_version }}
      run: |
        export TAG_VERSION=${PHP_VERSION:0:1}.${PHP_VERSION:1:1}
        echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login -u ${{ secrets.DOCKER_HUB_USER }} --password-stdin
        docker push laradock/php-fpm:${{ env.TAG_PREFIX }}-${TAG_VERSION}
        docker logout
